### ISSUE TITLE
Change Stream Resolution

### ISSUE THREAD

**Issue by cjjaeckson** [kwasmich/PICS#2]
Hi,
is it possible to increase or even change the resolution of the stream?
Thanks!

**Comment by kwasmich** [comment]
Unfortunately, it is currently not possible. My attempts so far have not been very successful.

**Comment by kwasmich** [comment]
Reevaluating this matter I found PICS not working on Raspberry Pi OS 11 (Bullseye) at all.
This is due to the removal of OpenMAX (which was used for hardware accelerated compression not depending on the image source) and the introduction of libcamera as the sole new camera API.
I made changes that work in combination with the **legacy camera** API.
There changing the resolution can be done in code `uvcCamera.c::458`.
Those changes come with limitations such as no support for cameras other than the Raspberry Pi Camera module.

**Comment by cjjaeckson** [comment]
Thx for the update! :)
